Fail if invalid spy is passed

diff --git a/shpy b/shpy
--- a/shpy
+++ b/shpy
@@ -86,14 +86,20 @@ getArgsForCall() {
         return 1
     fi
 
-    # local arg_file args call_number max name num_args path res saved_arg_files
+    local arg_file args call_number max name num_args path res saved_arg_files
 
-    # name=$1
+    name=$1
     # call_number=$(($2 - 1))
 
-    # path="$_shpy_spies_dir/$name/$call_number"
+    #path="$_shpy_spies_dir/$name/$call_number"
+    path="$_shpy_spies_dir/$name"
 
-    # if [ ! -d $(realpath ${path}) ]; then
+    if [ ! -d $(realpath ${path}) ]; then
+        echo "Error: spy '$name' has not been set up" >&2
+        return 1
+    fi
+
+    # if [ ! -d $(realpath ${path}/..) ]; then
       # return 1
     # fi
 
